### ISSUE TITLE
Niche and utility weapons

### ISSUE THREAD

**Issue by sakai4eva** [weblue/wanna_b_tierlist#18]
Certain weapons like the Sonicor (utility) have very little stopping power vs other similarly rated guns. Same goes for Mire, which is an Excalibur Exalted Blade special. 

Therefore these weapons should be rated separately or an indicator/prominent comment added to distinguish these weapons from sheer DPS weapons. 

Currently I'm envisaging a few options on how to denote these "special" weapons: 

**1. Usage of a x.5 tier.** 
1. a) Advantage of this is that we can also include the DPS potential of these weapons including and denote their utility. Obviously a tier-1 DPS weapon with special utility would remain in tier-1 without a doubt. Additionally, this makes it easy for those searching for a special weapon for a specific usage.
1. b) However, this option creates additional clutter and sub-classes which only retains the tier-level but not the fine ranking for each weapon. 

**2. Usage of a special marker like asterisk (*) to denote special weapons.** 
2. a) This has the advantage of retaining the weapon's DPS tier while considering their utility. This also reduces the tier level granularity and thus simplifies the layout of the tier list. 
2. b) However, special weapons will be lost in the mix and it will be hard to find them. 

**3. Usage of a separate list to rate utility/niche weapons outside of their DPS.** 
3. a) This would be an additional tab exclusively for niche/utility weapons that should not be rated alongside their DPS-based counterparts due to a special mechanic that makes them relevant in later content. This will make them easier to identify while allowing us to specify and explain the interactions that make these weapons special. 
3. b) However this would create an additional tab in an already very cluttered layout, which I do think we need to find a way to increase granularity for QoL purposes.

**Comment by weblue** [comment]
> 2. b) However, special weapons will be lost in the mix and it will be hard to find them.

The filter solves this issue when used correctly

2. will most likely be used, but I need to explore how to present the information. We already have a † symbol being used for Hunter Munitions, and there may be more indicators needed in the future. 

A special note tab may be used to clarify. This will be explored when we on board a new designer.

**Comment by weblue** [comment]
Currently, the issues to be tracked by the "Special Considerations" features will be: 

Unusual Riven Disposition

Extreme Synergy with Limited Mods

Niche Play Style

**Comment by weblue** [comment]
@sakai4eva I'm thinking of implementing this in the new list as a background color for the weapon and special note when expanded

what do you think?

**Comment by sakai4eva** [comment]
Expanded note would be great. 

I'm not sure we should use different colours unless we can come up with a good colour scheme. The site as it is looks quite standardized.
