### ISSUE TITLE
Granularity of weapon types in tier list

### ISSUE THREAD

**Issue by sakai4eva** [weblue/wanna_b_tierlist#19]
Currently the weapon tier list mixes up all the weapons based on primary, secondary and melee slots. 

A taxonomy style based on the warframe wiki injects clarity and familiarity with the weapon types based on their class, which would be very useful as a guide for picking which weapon to use in a sortie. 

![image](https://user-images.githubusercontent.com/21278297/33228219-a736be62-d1f0-11e7-9d57-8102256cd92c.png)

**Comment by weblue** [comment]
While the wiki presents its information using a double tab system, this system goes against design standards and isn't supported by Bootstrap (the underlying mechanism behind the tabbing functionality).

Usage of the filter should be used for now, however I'll be working on a way to improve visibility and give the user an understanding of how the filter system can be used to specify the weapon type (among other search features)

This is going to be left open ended as I don't have a designer for now

**Comment by GregariousJB** [comment]
Just my 2¢:

> Don't compromise your UX for the sake of following material design. Material design is meant to compliment your UX, not dictate it.

Whatever guidelines the wiki has broken are irrelevant. The end result allows users to very quickly and easily find the information they need. Furthermore, duplicating the system will make the system even easier since users are already used to it from the wiki.

http://jsfiddle.net/WK2qT/

**Comment by weblue** [comment]
Double tabs break Ctrl + f and filtering functionality

If you know what tier the weapon you're looking for is in, everything is fine; if you're searching for a weapon on the list, you have to cycle through tier tabs making the design unintuitive and disruptive to UX

**Comment by weblue** [comment]
A search could be made that allows tab switching, but there's members that prefer using ctrl+f over the filter function. Also, the code needed for tab switching would be non-trivial. I think a better designed solution is needed to implement this. 

As a note, when I tried to look at the given example, it looks like the wiki has actually gone away from nested tabs.

**Comment by malsf21** [comment]
Hm, you could have checkboxes that let you filter specific weapons? Kinda like what [Font Awesome does on their sidebar here](https://fontawesome.com/icons?d=gallery)? The code for that would be non-trivial but not too bad, and I don't think it causes too many design headaches. 

I think you'd implement this by having an Angular filter with ngFor? Thoughts @weblue ?

**Comment by sakai4eva** [comment]
@malsf21 wouldn't that require tagging all of the weapons?

**Comment by weblue** [comment]
@sakai4eva I don't think so since the weapons are already categorized; I think Matt's suggesting allowing users to select "tags" (categories) they want to appear in the tier list.

@malsf21 I think it might be easier than an ngFor, AngularJS supports filtering out of the box for stuff just like this, but it would be mean the port to Angular 2 would have to happen soon or we'd be locking ourselves deeper into JS

**Comment by weblue** [comment]
I think the idea is good for implementation. Gonna go for it after porting to non JS Angular

**Comment by malsf21** [comment]
Yes, the default behaviour would be as it is right now, and then checking a checkbox "starts" filtering. Since we already have all the tagged data we need (i.e. the weapon type/firing mode), we'd just need to run an angular filter. Sounds good to hold if off until we port over to Angular 2+.

**Comment by weblue** [comment]
this has now been implemented
