### ISSUE TITLE
Has Wyrm Prime been updated for its Negate mod?

### ISSUE THREAD

**Issue by JaneSmith** [weblue/wanna_b_tierlist#48]
I've noticed that Wyrm Prime is listed only under "Viable", beneath the Chesa Kubrow, while other sentinels like Carrier Prime and Helios Prime are listed under "Top". This seems strange to me, as the Negate mod allows a Wyrm Prime user to be nearly immune to status effects, which includes grabs and knockdowns. I see many players using this sentinel and speaking highly of it. The description of it on this website talks about its Crowd Dispersion ability only, making no mention of Negate. This makes me think that it hasn't been updated.

**Comment by weblue** [comment]
I believe it hasn't been looked at since the May update that brought Negate to it @sakai4eva

**Comment by malsf21** [comment]
Going to close this since it's stale.
