### ISSUE TITLE
Trailing comma in thelist.js

### ISSUE THREAD

**Issue by andersbrandt** [weblue/wanna_b_tierlist#52]
Around here:
Tombfinger - Mordant Meteor (Pax Seeker)

Trailing comma breaking JSON.parse

**Comment by weblue** [comment]
fixed, thanks!

**Comment by andersbrandt** [comment]
That was scary quick...
Im using your data in my app, feel free to check https://andersbrandt.se/warframe/helper/

**Comment by weblue** [comment]
currently giving me a 404, lmk when it's up!

**Comment by andersbrandt** [comment]
fixed, thanks!
