### ISSUE TITLE
Weapon used in crafting indicator

### ISSUE THREAD

**Issue by JovialMockingbird** [weblue/wanna_b_tierlist#53]
I use the tier list to see what old weapons to sell and at the moment I'm switching between the tier list and the wiki. I know it's not directly related to the weapon performance but 'crafting ingredient' seems like a useful and unobtrusive addition.

**Comment by malsf21** [comment]
This is definitely technically feasible (probably involves some wiki scraping?), though I'm not sure how much coding time we'll be able to dedicate to this (considering the Angular rewrite and all that). @weblue thoughts?

**Comment by weblue** [comment]
I think this is a decent idea. We have some higher priorities, but
adding more info to the list can't hurt.
