### ISSUE TITLE
Bolto missing from the list of secondaries

### ISSUE THREAD

**Issue by karpik123** [weblue/wanna_b_tierlist#59]
https://warframe.fandom.com/wiki/Bolto

I can see both Akbolto, but not Bolto. 
I noticed it missing because I have Riven for Bolto and wanted to see what bolto builds look like.

**Comment by malsf21** [comment]
Tagging in @sakai4eva

**Comment by sakai4eva** [comment]
Akbolto strictly outclass Bolto. 

Most single-pistols are horribad vs their dual counterparts with some notable exceptions and are therefore not tested.

**Comment by malsf21** [comment]
Should we mention this somewhere on the site? Not sure how often this gets asked.

**Comment by sakai4eva** [comment]
I think it's part of the FAQs in the discord. 

There was supposed to be a blog-post tab and a FAQ tab part of the tier list roadmap.
