### ISSUE TITLE
Menu Points can't be linked or Opened in new Tab

### ISSUE THREAD

**Issue by Serverfrog** [weblue/wanna_b_tierlist#78]
Sub-Pages, like FAQ or TestingMethods, can't be opened in new Tab (Middle-Mouseclick) or opened via link `https://www.cephalonwannab.com/oro`.
I remember it was some kind of Router Configuration in Angular to have this kind of feature

**Comment by malsf21** [comment]
Great catch @Serverfrog - this is a recurring issue that I've had to patch every now and then with how GitHub serves static sites (with Angular's routing). Working on it!

**Comment by malsf21** [comment]
I think I just fixed this in #78 - give it a shot now @Serverfrog!

**Comment by Serverfrog** [comment]
Looks like it works perfectly fine ;)
It isn't like you have many pages there :P

**Comment by malsf21** [comment]
Glad it works, thanks for the report!
